<div class="content">
	<h1 class="title_header">Geothermal</h1>
	<link rel="stylesheet" href="styles.css">
	<h2>What is it?</h2>
	<p>
		Geothermal power is generated by taking heat from deep within the Earth's crust and using it to turn water into steam. 
		That steam is then passed to a turbine, which does the actual energy generation.
		The heat can be transported through piping directly connected to the heat source (closed-loop system) or by pumping water to and from the heat source (open-loop system)[32].
	
	</p>
	<table class="pro_con">
		<tr>
			<th>
				<h2>Pros</h2>
			</th>
			<th>
				<h2>Cons</h2>
			</th>
		</tr>
		
		<tr>
			<td>			
				<ul>
					<li>Energy produced with negligible carbon emissions</li>
					<li>Since the heat's pulled from the Earth directly, and given how big the Earth is, there's no fuel to consider</li>
					<li>Once plant is established, little effort is needed to keep things rolling</li>
					<li>Provides jobs notably for the mining industry, which could be a boost for the industries in the Michigan U.P.</li>
					<li>Geothermal plants are scalable, so they can be built as large or small as needed[27]</li>
					<li>Economic benefits are uniform across location and income brackets[27]</li>
				</ul>
			</td>
			
			<td>
				<ul>
					<li>Risks other environmental emissions that could be dangerous to the surrounding environment. Type of geothermal plant informs the amount of these emissions[31]</li>
					<li>Lighting around plants contributes to light pollution[31]</li>
					<li>The up-front cost is very high, the sort of price that can only be handled by a corporation or governing body[27]</li>
					<li>Ability to use geothermal is limited based on hot-spots in a given area.</li>
					<li>Getting to hot-spots requires drilling, which can cause carbon emissions and lower the stability of the surrounding land.</li>
				</ul>
			</td>
		</tr>
	</table>

	<figure class="img_right">
		<img src="res/geothermal_heat_spots.jpg" width="700" height="450">
		<figcaption>Source: National Renwable Energy Laboratory [33]</figcaption>
	</figure>
	<h2>Should Michigan use it?</h2>
	<p>No. Geothermal is a bad fit for Michigan, but not because of the social and environmental concerns.
	While Michigan does have the sort of mining infrastructure to go looking for hot spots, the state itself simply 
	does not have the hot-spots necessary to allow for geothermal energy production to be a serious contender for Michigan's renewable energy.
	<br><br>If the state did have such hot spots, then their location matters greatly. If located near Michigan's agricultural sectors, then
	the risk of affecting nearby farmsteads is likely too great to make geothermal the driving force of renewable energy. Otherwise, that comes down
	to the question of if the people near such hotspots are willing to live with the consequences of constructing and running a geothermal power plant.</p>
</div>
